INSERT INTO ANIMAL (NOME_PROVISORIO, IDADE_ESTIMADA, RACA, DATA_ENTRADA, CONDICAO_CHEGADA, NOME_RECEBEDOR)
VALUES ('Caramelo', 2, 'SRD', current_date, 'Com parasitas', 'Alison');

INSERT INTO ANIMAL (NOME_PROVISORIO, IDADE_ESTIMADA, RACA, DATA_ENTRADA, DATA_ADOCAO, CONDICAO_CHEGADA, NOME_RECEBEDOR)
VALUES ('Pitoco', 4, 'SRD', current_date, current_date, 'Com parasitas', 'Alison');

