INSERT INTO ANIMAL (NOME_PROVISORIO, IDADE_ESTIMADA, RACA,TIPO, DATA_ENTRADA, CONDICAO_CHEGADA, NOME_RECEBEDOR)
VALUES ('Caramelo', 2, 'SRD','CANINO', current_date, 'Com parasitas', 'Alison');

INSERT INTO ANIMAL (NOME_PROVISORIO, IDADE_ESTIMADA, RACA,TIPO, DATA_ENTRADA, DATA_ADOCAO, CONDICAO_CHEGADA, NOME_RECEBEDOR)
VALUES ('Pitoco', 4, 'SRD','CANINO', current_date, current_date, 'Com parasitas', 'Alison');

INSERT INTO ANIMAL (NOME_PROVISORIO, IDADE_ESTIMADA, RACA,TIPO, DATA_ENTRADA, DATA_ADOCAO, CONDICAO_CHEGADA, NOME_RECEBEDOR)
VALUES ('Bolinha', 4, 'SRD','CANINO', current_date, current_date, 'Com parasitas', 'Juliana');

