CREATE TABLE IF NOT EXISTS ANIMAL
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome_provisorio  VARCHAR(255)                            NOT NULL,
    idade_estimada   VARCHAR(255)                            NOT NULL,
    raca             VARCHAR(255)                            NOT NULL,
    data_entrada     date                                    NOT NULL,
    data_adocao      date,
    condicao_chegada VARCHAR(255)                            NOT NULL,
    nome_recebedor   VARCHAR(255)                            NOT NULL,
    data_obito       VARCHAR(255),
    CONSTRAINT pk_animal PRIMARY KEY (id)
);